###

POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
    "email": "annnn1200@gmail.com",
    "password": "piouasd807"
}

###

GET http://localhost:3000/auth/4
Content-Type: application/json

###

GET http://localhost:3000/auth?email=annnn@gmail.com
Content-Type: application/json

###

PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "uahoo@yahoo.com"
}

###

DELETE http://localhost:3000/auth/10
Content-Type: application/json